# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  buildLinux:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7
      # Runs a set of commands using the runners shell
      - name: Install Haxelib
        run: |
          sudo apt-get install libvlc-dev
          sudo apt-get install libvlccore-dev
          
          haxelib setup ~/haxelib
          haxelib install tjson --quiet
          haxelib install hxjsonast --quiet
          haxelib install flxgif --quiet
          haxelib install flixel 6.1.0
          haxelib install lime 8.2.2
          haxelib install format
          haxelib install hxp
          haxelib install openfl 9.4.1
          haxelib install hxvlc --quiet --skip-dependencies
          haxelib run lime setup flixel
          haxelib install flixel-tools 1.5.1
          haxelib install flixel-addons 3.3.2
          haxelib install hxdiscord_rpc 1.2.4
          haxelib git hxcpp https://github.com/FunkinCrew/hxcpp
          haxelib git flxsoundfilters https://github.com/TheZoroForce240/FlxSoundFilters.git
          haxelib git rulescript https://github.com/Kriptel/RuleScript.git dev
          haxelib git hscript https://github.com/HaxeFoundation/hscript.git
          haxelib git flixel-animate https://github.com/MaybeMaru/flixel-animate.git 40ea31d4b598a01411c8c96f52702e090478ba1f
          haxelib git linc_luajit https://github.com/superpowers04/linc_luajit.git
          haxelib list
      - name: Compile
        run: haxelib run lime build Project.xml linux
      - name: Publish Artifact
        uses: actions/upload-artifact@main
        with:
          name: linuxBuild
          path: 'export/release/linux/bin'
  buildWindows:
    runs-on: windows-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7
      # Runs a set of commands using the runners shell
      - name: Install Haxelib
        run: |
          haxelib setup C:/haxelib
          haxelib install tjson --quiet
          haxelib install hxjsonast --quiet
          haxelib install flxgif --quiet
          haxelib install flixel 6.1.0
          haxelib git lime https://github.com/GreenColdTea/lime-9.0.0
          haxelib install format
          haxelib install hxp
          haxelib install openfl 9.4.1
          haxelib install hxvlc --quiet --skip-dependencies
          haxelib run lime setup flixel
          haxelib install flixel-tools 1.5.1
          haxelib install flixel-addons 3.3.2
          haxelib install hxdiscord_rpc 1.2.4
          haxelib git hxcpp https://github.com/FunkinCrew/hxcpp
          haxelib git flxsoundfilters https://github.com/TheZoroForce240/FlxSoundFilters.git
          haxelib git rulescript https://github.com/Kriptel/RuleScript.git dev
          haxelib git hscript https://github.com/HaxeFoundation/hscript.git
          haxelib git sl-windows-api https://github.com/GreenColdTea/windows-api-improved.git
          haxelib git flixel-animate https://github.com/MaybeMaru/flixel-animate.git 40ea31d4b598a01411c8c96f52702e090478ba1f
          haxelib git linc_luajit https://github.com/superpowers04/linc_luajit.git
          haxelib list
        shell: cmd
      - name: Compile
        run: haxelib run lime build windows
        
             echo y
      - name: Publish Artifact
        uses: actions/upload-artifact@main
        with:
          name: windowsBuild
          path: export/release/windows/bin
  buildMac:
    runs-on: macos-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7
      # Runs a set of commands using the runners shell
      - name: Install Haxelib
        run: |
          haxelib install tjson --quiet
          haxelib install hxjsonast --quiet
          haxelib install flxgif --quiet
          haxelib install flixel 6.1.0
          haxelib install lime 8.2.2
          haxelib install format
          haxelib install hxp
          haxelib install openfl 9.4.1
          haxelib install hxvlc --quiet --skip-dependencies
          haxelib run lime setup flixel
          haxelib install flixel-tools 1.5.1
          haxelib install flixel-addons 3.3.2
          haxelib install hxdiscord_rpc 1.2.4
          haxelib git hxcpp https://github.com/FunkinCrew/hxcpp
          haxelib git flxsoundfilters https://github.com/TheZoroForce240/FlxSoundFilters.git
          haxelib git rulescript https://github.com/Kriptel/RuleScript.git dev
          haxelib git hscript https://github.com/HaxeFoundation/hscript.git
          haxelib git flixel-animate https://github.com/MaybeMaru/flixel-animate.git 40ea31d4b598a01411c8c96f52702e090478ba1f
          haxelib git linc_luajit https://github.com/superpowers04/linc_luajit.git
          haxelib list
      - name: Compile
        run: haxelib run lime build mac
      - name: Publish Artifact
        uses: actions/upload-artifact@main
        with:
          name: macBuild
          path: export/release/macos/bin
